name: Build and Push Docker Image on Pull Request

on:
  push:
    branches:
      - main # Replace with the name of the branch you want to build

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: pavankagupati2001
          password: Pavan@2001

      - name: Build and Push Docker Image
        run: docker build -t pavannodeapp:v1.1.1
