# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: echo "hello"
    - name: Login to Container Registry
    - uses: docker/login-action@v1
      with:
        registry: docker.io
        username: pavankagupati2001
        password: Pavan@2001
    - name: build image
     - uses: docker/build-action@v1
     - run: sudo docker build -t pavannodeapp:v11.1 .
     - run: sudo docker push pavankagupati2001/pavanrepo:pavannodeapp:v11.1

