name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploying
        working-directory: _work
        run: sudo docker build -t nodeapp:v1.1.1 .
