name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploying
        run: cd _work/nodeapp/nodeapp
        
